#!/bin/bash
set -e
sudo hostnamectl set-hostname docker
sudo apt update -y
sudo apt install -y docker.io
sudo systemctl start docker
sudo systemctl enable docker
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
  -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo usermod -aG docker ubuntu
newgrp docker
docker --version
docker-compose --version
sudo docker info
sudo docker ps

🧱 2. Create Your Project Folder
Create a clean directory to hold your setup:
mkdir devops-stack
cd devops-stack

3.Then create your docker-compose.yml file:
nano docker-compose.yml

4. Paste this complete version 👇:

version: '3.8'

networks:
  devops-net:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data:

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: myjenkins
    ports:
      - "8007:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - devops-net
    restart: unless-stopped

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonar
    ports:
      - "8008:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - devops-net
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8009:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - devops-net
    restart: unless-stopped